import actions from "./actions.js";
import mutations from "./mutations.js";
import getters from "./getters.js";

export default {
  namespaced: true,
  state() {
    return {
      normal: false,
      shiny: false,
      alpha: false,
      shinyAlpha: false,
      marked: false,
      shinyMarked: false,
      pokerus: false,
      shinyPokerus: false,
      zeroIv: false,
      shinyZeroIv: false,
      sixIv: false,
      shinySixIv: false,
      favorite: false,

      teraBug: false,
      teraDark: false,
      teraDragon: false,
      teraElectric: false,
      teraFairy: false,
      teraFighting: false,
      teraFire: false,
      teraFlying: false,
      teraGhost: false,
      teraGrass: false,
      teraGround: false,
      teraIce: false,
      teraNormal: false,
      teraPoison: false,
      teraPsychic: false,
      teraRock: false,
      teraSteel: false,
      teraWater: false,
      teraShinyBug: false,
      teraShinyDark: false,
      teraShinyDragon: false,
      teraShinyElectric: false,
      teraShinyFairy: false,
      teraShinyFighting: false,
      teraShinyFire: false,
      teraShinyFlying: false,
      teraShinyGhost: false,
      teraShinyGrass: false,
      teraShinyGround: false,
      teraShinyIce: false,
      teraShinyNormal: false,
      teraShinyPoison: false,
      teraShinyPsychic: false,
      teraShinyRock: false,
      teraShinySteel: false,
      teraShinyWater: false,

      shinyAvailable: false,
      alphaAvailable: false,
      shinyAlphaAvailable: false,
      markedAvailable: false,
      shinyMarkedAvailable: false,
      teraBugAvailable: false,
      teraDarkAvailable: false,
      teraDragonAvailable: false,
      teraElectricAvailable: false,
      teraFairyAvailable: false,
      teraFightingAvailable: false,
      teraFireAvailable: false,
      teraFlyingAvailable: false,
      teraGhostAvailable: false,
      teraGrassAvailable: false,
      teraGroundAvailable: false,
      teraIceAvailable: false,
      teraNormalAvailable: false,
      teraPoisonAvailable: false,
      teraPsychicAvailable: false,
      teraRockAvailable: false,
      teraSteelAvailable: false,
      teraWaterAvailable: false,
      teraShinyBugAvailable: false,
      teraShinyDarkAvailable: false,
      teraShinyDragonAvailable: false,
      teraShinyElectricAvailable: false,
      teraShinyFairyAvailable: false,
      teraShinyFightingAvailable: false,
      teraShinyFireAvailable: false,
      teraShinyFlyingAvailable: false,
      teraShinyGhostAvailable: false,
      teraShinyGrassAvailable: false,
      teraShinyGroundAvailable: false,
      teraShinyIceAvailable: false,
      teraShinyNormalAvailable: false,
      teraShinyPoisonAvailable: false,
      teraShinyPsychicAvailable: false,
      teraShinyRockAvailable: false,
      teraShinySteelAvailable: false,
      teraShinyWaterAvailable: false
    };
  },
  mutations,
  actions,
  getters
};
