const moreInfoAvailability =
  {
    normal: true,
    shiny: true,
    alpha: true,
    shinyAlpha: true,
    marked: true,
    shinyMarked: true,
    pokerus: true,
    shinyPokerus: true,
    sixIv: true,
    shinySixIv: true,
    zeroIv: true,
    shinyZeroIv: true,

    teraBug: true,
    teraDark: true,
    teraDragon: true,
    teraElectric: true,
    teraFairy: true,
    teraFighting: true,
    teraFire: true,
    teraFlying: true,
    teraGhost: true,
    teraGrass: true,
    teraGround: true,
    teraIce: true,
    teraNormal: true,
    teraPoison: true,
    teraPsychic: true,
    teraRock: true,
    teraSteel: true,
    teraWater: true,
    teraShinyBug: true,
    teraShinyDark: true,
    teraShinyDragon: true,
    teraShinyElectric: true,
    teraShinyFairy: true,
    teraShinyFighting: true,
    teraShinyFire: true,
    teraShinyFlying: true,
    teraShinyGhost: true,
    teraShinyGrass: true,
    teraShinyGround: true,
    teraShinyIce: true,
    teraShinyNormal: true,
    teraShinyPoison: true,
    teraShinyPsychic: true,
    teraShinyRock: true,
    teraShinySteel: true,
    teraShinyWater: true
  };

export { moreInfoAvailability };