export type StatisticsCountType = {
  total: number,
  longestTime: { name: string | undefined, total: number, category?: string | undefined },
  shortestTime: { name: string | undefined, total: number, category?: string | undefined },
  shortestCount: { name: string | undefined, total: number, category?: string | undefined },
  longestCount: { name: string | undefined, total: number, category?: string | undefined }
}

export type StatisticsGenerationType = {
  all: number,
  normal: number,
  shiny: number,
  alpha: number,
  shinyAlpha: number,
  marked: number,
  shinyMarked: number,
  pokerus: number,
  shinyPokerus: number,
  sixIv: number,
  shinySixIv: number,
  zeroIv: number,
  shinyZeroIv: number,
  teraAll: number,
  teraBug: number,
  teraDark: number,
  teraDragon: number,
  teraElectric: number,
  teraFairy: number,
  teraFighting: number,
  teraFire: number,
  teraFlying: number,
  teraGhost: number,
  teraGrass: number,
  teraGround: number,
  teraIce: number,
  teraNormal: number,
  teraPoison: number,
  teraPsychic: number,
  teraRock: number,
  teraSteel: number,
  teraWater: number,
  teraShinyAll: number,
  teraShinyBug: number,
  teraShinyDark: number,
  teraShinyDragon: number,
  teraShinyElectric: number,
  teraShinyFairy: number,
  teraShinyFighting: number,
  teraShinyFire: number,
  teraShinyFlying: number,
  teraShinyGhost: number,
  teraShinyGrass: number,
  teraShinyGround: number,
  teraShinyIce: number,
  teraShinyNormal: number,
  teraShinyPoison: number,
  teraShinyPsychic: number,
  teraShinyRock: number,
  teraShinySteel: number,
  teraShinyWater: number
}
